services:
  app:
    build: .
    container_name: otp-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/otpdb
      - REDIS_URL=redis://redis:6379
      - OTP_EXPIRY=300
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: otp-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - backend

  redis:
    image: redis:7
    container_name: otp-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend

volumes:
  mongodb:
  redisdata:

networks:
  backend:
    driver: bridge
